@baseUrl = http://localhost:3500

@ContentType = application/json

# POST {{baseUrl}}/register
# content-type: application/json

# {
#     "user": "Vijay",
#     "pwd": "Mahendran"
# }

# POST {{baseUrl}}/auth
# content-type: application/json

# {
#     "user": "Vijay",
#     "pwd": "Mahendra"
# }