@baseUrl = http://localhost:3500

@ContentType = application/json

PUT {{baseUrl}}/employees
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6Iktpc2hhbiIsInJvbGVzIjpbMjAwMSwxOTg0XX0sImlhdCI6MTc3MjkxMDQ1NywiZXhwIjoxNzcyOTEwNDg3fQ.gmWMUnfDoTkKCk8pTCwqgi5oVi3o-Kz4U-1J4EfohNE

{
    "id": 2,
    "firstname": "Kishan"
}